server:
  port: 8100 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  retry:
    instances:
      foo-bar:
        max-attempts: 3
        waitDuration: 500
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true    
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: book_service
    user: root
    password: root
springdoc:
 api-docs:
  path: /book-service/v3/api-docs #these urls will used to load the swagger ui of this service by the api gateway
 swagger-ui:
  enabled: true
  path: /swagger-ui.html
logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
    # com:
    #   example:
    #     bookservice: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'  
management:
  metrics:
    distribution:
      percentiles-histogram:
        http-server-requests: true        
  # endpoints:
  #   web:
  #     exposure:
  #       include: '*'
  tracing:
    sampling:
      probability: 1.0      
    # propagation:
    #   type: w3c
    # baggage:
    #   enabled: true
    # enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411

# management.tracing.sampling.probability=1.0 # para enviar 100% da amostra
# management.tracing.propagation.type=w3c 
# management.tracing.baggage.enabled=true
# management.tracing.enabled=true
# management.zipkin.tracing.endpoint=SEU_ZIPKIN/api/v2/spans # alterar o endereco do Zipkin